export const FETCH_FILTER_OPTIONS = 'FETCH_FILTER_OPTIONS';
export const APPLY_FILTER = 'APPLY_FILTER';
export const UNAPPLY_FILTER = 'UNAPPLY_FILTER';
export const CLEAR_ALL_FILTERS = 'CLEAR_ALL_FILTERS';
export const FETCH_RESOURCES = 'FETCH_RESOURCES';
export const FETCH_RESOURCE = 'FETCH_RESOURCE';
