export const SET_USER_SIGNIN = 'SET_USER_SIGNIN';
export const SET_SETTINGS_AUTH = 'SET_SETTINGS_AUTH';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
export const SET_BOOKMARK = 'SET_BOOKMARK';
export const SET_PREVIEW_MODE = 'SET_PREVIEW_MODE';
