export const SET_THEMES = 'SET_THEMES';
export const SET_RESOURCES = 'SET_RESOURCES';
export const SET_USER_SIGNIN = 'SET_USER_SIGNIN';
export const SET_SETTINGS_AUTH = 'SET_SETTINGS_AUTH';
export const SET_BOOKMARKS = 'SET_BOOKMARKS';
